name: Django CI

# Configure Events
on:
  push:
    branches: ["dev"]
  pull_request_target: # To be able to access the secrets
    branches: ["dev"]
    types: [opened] # run workflow only for opened pull requests.
    paths: # run workflow only when .py files are modified
      - "**.py"

env: ${{ secrets }}

jobs:
  build: # job id
    runs-on: ubuntu-latest # The OS to build your project on
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ["3.11"] # Python version to build the applciation

    env: # environment variables.
      # Use `secrets` to access secrets from  settings
      # Use `vars` to access variables from settings
      DB_USER: ${{ secrets.DB_USER }}
      DB_PWD: ${{ secrets.DB_PWD }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    services: # If you had database connection issues
      postgres_main:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PWD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        # options: >-
        #   --health-cmd pg_isready
        #   --health-interval 10s
        #   --health-retries 4

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
